/*
 * Yes Identity
 * Welcome to Yes Identity API documentation.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.yesidentity.sdk.api;

import com.yesidentity.sdk.invoker.ApiException;
import com.yesidentity.sdk.model.ErrorResponseModel;
import java.io.File;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for QrCodeApi
 */
@Ignore
public class QrCodeApiTest {

    private final QrCodeApi api = new QrCodeApi();

    
    /**
     * Create QR Code
     *
     * Create QR Code
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createQRCodeTest() throws ApiException {
        String authToken = null;
        Integer size = null;
                File response = api.createQRCode(authToken, size);
        // TODO: test validations
    }
    
}
