/*
 * Yes Identity
 * Welcome to Yes Identity API documentation.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.yesidentity.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Client assertion type
 */
@JsonAdapter(ClientAssertionTypeModel.Adapter.class)
public enum ClientAssertionTypeModel {
  
  URN_IETF_PARAMS_OAUTH_CLIENT_ASSERTION_TYPE_JWT_BEARER("urn:ietf:params:oauth:client-assertion-type:jwt-bearer");

  private String value;

  ClientAssertionTypeModel(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ClientAssertionTypeModel fromValue(String value) {
    for (ClientAssertionTypeModel b : ClientAssertionTypeModel.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ClientAssertionTypeModel> {
    @Override
    public void write(final JsonWriter jsonWriter, final ClientAssertionTypeModel enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ClientAssertionTypeModel read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ClientAssertionTypeModel.fromValue(value);
    }
  }
}

