/*
 * Yes Identity
 * Welcome to Yes Identity API documentation.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.yesidentity.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DeviceModel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-01T07:44:54.268733600+01:00[Europe/Stockholm]")
public class DeviceModel {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PHONE_NUMBER = "phone_number";
  @SerializedName(SERIALIZED_NAME_PHONE_NUMBER)
  private String phoneNumber;

  public static final String SERIALIZED_NAME_REGISTRATION_TOKEN = "registration_token";
  @SerializedName(SERIALIZED_NAME_REGISTRATION_TOKEN)
  private String registrationToken;

  public static final String SERIALIZED_NAME_BIOMETRICS_ENABLED = "biometrics_enabled";
  @SerializedName(SERIALIZED_NAME_BIOMETRICS_ENABLED)
  private Boolean biometricsEnabled;

  public static final String SERIALIZED_NAME_ACTIVE = "active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  private Boolean active;

  public static final String SERIALIZED_NAME_BLOCKED = "blocked";
  @SerializedName(SERIALIZED_NAME_BLOCKED)
  private Boolean blocked;

  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  private Long created;

  public static final String SERIALIZED_NAME_UPDATED = "updated";
  @SerializedName(SERIALIZED_NAME_UPDATED)
  private Long updated;

  public static final String SERIALIZED_NAME_LAST_USED = "last_used";
  @SerializedName(SERIALIZED_NAME_LAST_USED)
  private Long lastUsed;

  public static final String SERIALIZED_NAME_PUBLIC_KEY = "public_key";
  @SerializedName(SERIALIZED_NAME_PUBLIC_KEY)
  private String publicKey;

  public static final String SERIALIZED_NAME_SECURITY_CODE = "security_code";
  @SerializedName(SERIALIZED_NAME_SECURITY_CODE)
  private String securityCode;

  public static final String SERIALIZED_NAME_SECURITY_CODE_ENABLED = "security_code_enabled";
  @SerializedName(SERIALIZED_NAME_SECURITY_CODE_ENABLED)
  private Boolean securityCodeEnabled;

  public DeviceModel() { 
  }

  
  public DeviceModel(
     String id, 
     Boolean active, 
     Boolean blocked, 
     Long created, 
     Long updated, 
     Long lastUsed, 
     Boolean securityCodeEnabled
  ) {
    this();
    this.id = id;
    this.active = active;
    this.blocked = blocked;
    this.created = created;
    this.updated = updated;
    this.lastUsed = lastUsed;
    this.securityCodeEnabled = securityCodeEnabled;
  }

   /**
   * Device id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Device id")

  public String getId() {
    return id;
  }




  public DeviceModel name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Device name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Device name")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public DeviceModel phoneNumber(String phoneNumber) {
    
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Phone number
   * @return phoneNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Phone number")

  public String getPhoneNumber() {
    return phoneNumber;
  }


  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  public DeviceModel registrationToken(String registrationToken) {
    
    this.registrationToken = registrationToken;
    return this;
  }

   /**
   * Push token
   * @return registrationToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Push token")

  public String getRegistrationToken() {
    return registrationToken;
  }


  public void setRegistrationToken(String registrationToken) {
    this.registrationToken = registrationToken;
  }


  public DeviceModel biometricsEnabled(Boolean biometricsEnabled) {
    
    this.biometricsEnabled = biometricsEnabled;
    return this;
  }

   /**
   * Whether public key is locked by biometrics or not
   * @return biometricsEnabled
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Whether public key is locked by biometrics or not")

  public Boolean getBiometricsEnabled() {
    return biometricsEnabled;
  }


  public void setBiometricsEnabled(Boolean biometricsEnabled) {
    this.biometricsEnabled = biometricsEnabled;
  }


   /**
   * Active device
   * @return active
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Active device")

  public Boolean getActive() {
    return active;
  }




   /**
   * Blocked device
   * @return blocked
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Blocked device")

  public Boolean getBlocked() {
    return blocked;
  }




   /**
   * Created date. Measured in seconds since the Unix epoch
   * @return created
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Created date. Measured in seconds since the Unix epoch")

  public Long getCreated() {
    return created;
  }




   /**
   * Updated date. Measured in seconds since the Unix epoch
   * @return updated
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Updated date. Measured in seconds since the Unix epoch")

  public Long getUpdated() {
    return updated;
  }




   /**
   * Last used date. Measured in seconds since the Unix epoch
   * @return lastUsed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Last used date. Measured in seconds since the Unix epoch")

  public Long getLastUsed() {
    return lastUsed;
  }




  public DeviceModel publicKey(String publicKey) {
    
    this.publicKey = publicKey;
    return this;
  }

   /**
   * Public key
   * @return publicKey
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Public key")

  public String getPublicKey() {
    return publicKey;
  }


  public void setPublicKey(String publicKey) {
    this.publicKey = publicKey;
  }


  public DeviceModel securityCode(String securityCode) {
    
    this.securityCode = securityCode;
    return this;
  }

   /**
   * Security code
   * @return securityCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Security code")

  public String getSecurityCode() {
    return securityCode;
  }


  public void setSecurityCode(String securityCode) {
    this.securityCode = securityCode;
  }


   /**
   * Security code enabled
   * @return securityCodeEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Security code enabled")

  public Boolean getSecurityCodeEnabled() {
    return securityCodeEnabled;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceModel device = (DeviceModel) o;
    return Objects.equals(this.id, device.id) &&
        Objects.equals(this.name, device.name) &&
        Objects.equals(this.phoneNumber, device.phoneNumber) &&
        Objects.equals(this.registrationToken, device.registrationToken) &&
        Objects.equals(this.biometricsEnabled, device.biometricsEnabled) &&
        Objects.equals(this.active, device.active) &&
        Objects.equals(this.blocked, device.blocked) &&
        Objects.equals(this.created, device.created) &&
        Objects.equals(this.updated, device.updated) &&
        Objects.equals(this.lastUsed, device.lastUsed) &&
        Objects.equals(this.publicKey, device.publicKey) &&
        Objects.equals(this.securityCode, device.securityCode) &&
        Objects.equals(this.securityCodeEnabled, device.securityCodeEnabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, phoneNumber, registrationToken, biometricsEnabled, active, blocked, created, updated, lastUsed, publicKey, securityCode, securityCodeEnabled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceModel {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    registrationToken: ").append(toIndentedString(registrationToken)).append("\n");
    sb.append("    biometricsEnabled: ").append(toIndentedString(biometricsEnabled)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    blocked: ").append(toIndentedString(blocked)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    lastUsed: ").append(toIndentedString(lastUsed)).append("\n");
    sb.append("    publicKey: ").append(toIndentedString(publicKey)).append("\n");
    sb.append("    securityCode: ").append(toIndentedString(securityCode)).append("\n");
    sb.append("    securityCodeEnabled: ").append(toIndentedString(securityCodeEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

