/*
 * Yes Identity
 * Welcome to Yes Identity API documentation.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.yesidentity.sdk.model;

import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ClientAssertionTypeModel
 */
public class ClientAssertionTypeModelTest {
    /**
     * Model tests for ClientAssertionTypeModel
     */
    @Test
    public void testClientAssertionTypeModel() {
        // TODO: test ClientAssertionTypeModel
    }

}
