/*
 * Yes Identity
 * Welcome to Yes Identity API documentation.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.yesidentity.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DeviceModel
 */
public class DeviceModelTest {
    private final DeviceModel model = new DeviceModel();

    /**
     * Model tests for DeviceModel
     */
    @Test
    public void testDeviceModel() {
        // TODO: test DeviceModel
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    public void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'registrationToken'
     */
    @Test
    public void registrationTokenTest() {
        // TODO: test registrationToken
    }

    /**
     * Test the property 'biometricsEnabled'
     */
    @Test
    public void biometricsEnabledTest() {
        // TODO: test biometricsEnabled
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'blocked'
     */
    @Test
    public void blockedTest() {
        // TODO: test blocked
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'updated'
     */
    @Test
    public void updatedTest() {
        // TODO: test updated
    }

    /**
     * Test the property 'lastUsed'
     */
    @Test
    public void lastUsedTest() {
        // TODO: test lastUsed
    }

    /**
     * Test the property 'publicKey'
     */
    @Test
    public void publicKeyTest() {
        // TODO: test publicKey
    }

    /**
     * Test the property 'securityCode'
     */
    @Test
    public void securityCodeTest() {
        // TODO: test securityCode
    }

    /**
     * Test the property 'securityCodeEnabled'
     */
    @Test
    public void securityCodeEnabledTest() {
        // TODO: test securityCodeEnabled
    }

}
