/*
 * Yes Identity
 * Welcome to Yes Identity API documentation.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.yesidentity.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OpenIDConfigurationModel
 */
public class OpenIDConfigurationModelTest {
    private final OpenIDConfigurationModel model = new OpenIDConfigurationModel();

    /**
     * Model tests for OpenIDConfigurationModel
     */
    @Test
    public void testOpenIDConfigurationModel() {
        // TODO: test OpenIDConfigurationModel
    }

    /**
     * Test the property 'authorizationEndpoint'
     */
    @Test
    public void authorizationEndpointTest() {
        // TODO: test authorizationEndpoint
    }

    /**
     * Test the property 'tokenEndpoint'
     */
    @Test
    public void tokenEndpointTest() {
        // TODO: test tokenEndpoint
    }

    /**
     * Test the property 'issuer'
     */
    @Test
    public void issuerTest() {
        // TODO: test issuer
    }

    /**
     * Test the property 'jwksUri'
     */
    @Test
    public void jwksUriTest() {
        // TODO: test jwksUri
    }

    /**
     * Test the property 'backchannelTokenDeliveryModesSupported'
     */
    @Test
    public void backchannelTokenDeliveryModesSupportedTest() {
        // TODO: test backchannelTokenDeliveryModesSupported
    }

    /**
     * Test the property 'backchannelAuthenticationRequestSigningAlgValuesSupported'
     */
    @Test
    public void backchannelAuthenticationRequestSigningAlgValuesSupportedTest() {
        // TODO: test backchannelAuthenticationRequestSigningAlgValuesSupported
    }

    /**
     * Test the property 'scopesSupported'
     */
    @Test
    public void scopesSupportedTest() {
        // TODO: test scopesSupported
    }

    /**
     * Test the property 'grantTypesSupported'
     */
    @Test
    public void grantTypesSupportedTest() {
        // TODO: test grantTypesSupported
    }

    /**
     * Test the property 'tokenEndpointAuthMethodsSupported'
     */
    @Test
    public void tokenEndpointAuthMethodsSupportedTest() {
        // TODO: test tokenEndpointAuthMethodsSupported
    }

    /**
     * Test the property 'tokenEndpointAuthSigningAlgValuesSupported'
     */
    @Test
    public void tokenEndpointAuthSigningAlgValuesSupportedTest() {
        // TODO: test tokenEndpointAuthSigningAlgValuesSupported
    }

}
