/*
 * Yes Identity
 * Welcome to Yes Identity API documentation.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.yesidentity.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.yesidentity.sdk.model.ClientAssertionTypeModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TokenRequestModel
 */
public class TokenRequestModelTest {
    private final TokenRequestModel model = new TokenRequestModel();

    /**
     * Model tests for TokenRequestModel
     */
    @Test
    public void testTokenRequestModel() {
        // TODO: test TokenRequestModel
    }

    /**
     * Test the property 'grantType'
     */
    @Test
    public void grantTypeTest() {
        // TODO: test grantType
    }

    /**
     * Test the property 'authReqId'
     */
    @Test
    public void authReqIdTest() {
        // TODO: test authReqId
    }

    /**
     * Test the property 'scope'
     */
    @Test
    public void scopeTest() {
        // TODO: test scope
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    public void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'clientAssertion'
     */
    @Test
    public void clientAssertionTest() {
        // TODO: test clientAssertion
    }

    /**
     * Test the property 'clientAssertionType'
     */
    @Test
    public void clientAssertionTypeTest() {
        // TODO: test clientAssertionType
    }

}
